-- ============================================================
-- Abdul Sattar Sons POS
-- Initial Version-Controlled Database Schema
-- Date: 2026-07-31
--
-- Based on the existing Supabase PostgreSQL database.
-- ============================================================


-- ============================================================
-- 1. PRODUCTS
-- ============================================================

CREATE TABLE public.products (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL,
    brand TEXT,
    barcode TEXT UNIQUE,
    purchase_price NUMERIC NOT NULL,
    selling_price NUMERIC NOT NULL,
    stock INTEGER DEFAULT 0,
    unit TEXT,
    low_stock INTEGER DEFAULT 5,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT products_purchase_price_nonnegative
        CHECK (purchase_price >= 0),

    CONSTRAINT products_selling_price_nonnegative
        CHECK (selling_price >= 0),

    CONSTRAINT products_stock_nonnegative
        CHECK (stock >= 0),

    CONSTRAINT products_low_stock_nonnegative
        CHECK (low_stock >= 0)
);


-- ============================================================
-- 2. CUSTOMERS
-- ============================================================

CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_active BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT customers_name_not_blank
        CHECK (length(trim(name)) > 0),

    CONSTRAINT customers_phone_not_blank
        CHECK (length(trim(phone)) > 0)
);


-- ============================================================
-- 3. SALES
-- ============================================================

CREATE TABLE public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT NOT NULL UNIQUE,
    subtotal NUMERIC NOT NULL DEFAULT 0,
    discount NUMERIC NOT NULL DEFAULT 0,
    total NUMERIC NOT NULL DEFAULT 0,
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    amount_paid NUMERIC NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    amount_received NUMERIC,
    change_due NUMERIC NOT NULL DEFAULT 0,
    customer_id BIGINT,

    CONSTRAINT sales_amount_paid_check
        CHECK (amount_paid >= 0),

    CONSTRAINT sales_discount_check
        CHECK (discount >= 0),

    CONSTRAINT sales_discount_not_greater_than_subtotal
        CHECK (discount <= subtotal),

    CONSTRAINT sales_subtotal_check
        CHECK (subtotal >= 0),

    CONSTRAINT sales_total_check
        CHECK (total >= 0),

    CONSTRAINT sales_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES public.customers(id)
        ON DELETE RESTRICT
);


-- ============================================================
-- 4. SALE ITEMS
-- ============================================================

CREATE TABLE public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    product_id BIGINT,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit TEXT,
    unit_price NUMERIC NOT NULL,
    unit_cost NUMERIC NOT NULL,
    line_total NUMERIC NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT sale_items_quantity_check
        CHECK (quantity > 0),

    CONSTRAINT sale_items_unit_price_check
        CHECK (unit_price >= 0),

    CONSTRAINT sale_items_unit_cost_check
        CHECK (unit_cost >= 0),

    CONSTRAINT sale_items_line_total_check
        CHECK (line_total >= 0),

    CONSTRAINT sale_items_sale_id_fkey
        FOREIGN KEY (sale_id)
        REFERENCES public.sales(id)
        ON DELETE CASCADE,

    CONSTRAINT sale_items_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES public.products(id)
        ON DELETE SET NULL
);


-- ============================================================
-- 5. INVOICE NUMBER SEQUENCE
-- ============================================================

CREATE SEQUENCE public.invoice_number_seq;


-- ============================================================
-- 6. GENERATE INVOICE NUMBER
-- ============================================================

CREATE OR REPLACE FUNCTION public.generate_invoice_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $function$
DECLARE
    next_number BIGINT;
BEGIN
    next_number := nextval('invoice_number_seq');

    RETURN 'INV-' || LPAD(next_number::TEXT, 6, '0');
END;
$function$;


-- ============================================================
-- 7. COMPLETE SALE
-- ============================================================

CREATE OR REPLACE FUNCTION public.complete_sale(
    p_items JSONB,
    p_discount NUMERIC DEFAULT 0,
    p_payment_method TEXT DEFAULT 'Cash'::TEXT,
    p_amount_paid NUMERIC DEFAULT NULL::NUMERIC,
    p_notes TEXT DEFAULT NULL::TEXT,
    p_customer_id BIGINT DEFAULT NULL::BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
AS $function$
DECLARE
    v_sale_id BIGINT;
    v_invoice_number TEXT;

    v_subtotal NUMERIC(12,2);
    v_total NUMERIC(12,2);

    v_amount_received NUMERIC(12,2);
    v_amount_paid NUMERIC(12,2);
    v_change_due NUMERIC(12,2);

    v_item RECORD;
BEGIN

    -- 1. Validate cart
    IF p_items IS NULL
       OR jsonb_typeof(p_items) <> 'array'
       OR jsonb_array_length(p_items) = 0
    THEN
        RAISE EXCEPTION 'Cart cannot be empty.';
    END IF;

    -- 2. Validate discount
    IF p_discount IS NULL OR p_discount < 0 THEN
        RAISE EXCEPTION 'Discount cannot be negative.';
    END IF;

    -- 3. Validate customer when supplied
    IF p_customer_id IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1
            FROM customers
            WHERE id = p_customer_id
              AND is_active = true
        ) THEN
            RAISE EXCEPTION
                'Selected customer was not found or is inactive.';
        END IF;
    END IF;

    -- 4. Validate cart items
    IF EXISTS (
        SELECT 1
        FROM jsonb_array_elements(p_items) AS item
        WHERE
            (item ->> 'product_id') IS NULL
            OR (item ->> 'quantity') IS NULL
            OR (item ->> 'product_id') !~ '^[0-9]+$'
            OR (item ->> 'quantity') !~ '^[0-9]+$'
            OR (item ->> 'product_id')::BIGINT <= 0
            OR (item ->> 'quantity')::INTEGER <= 0
    ) THEN
        RAISE EXCEPTION
            'Every cart item must have a valid product ID and quantity greater than zero.';
    END IF;

    -- 5. Aggregate duplicate products
    CREATE TEMP TABLE temp_sale_items
    ON COMMIT DROP
    AS
    SELECT
        (item ->> 'product_id')::BIGINT AS product_id,
        SUM(
            (item ->> 'quantity')::INTEGER
        )::INTEGER AS quantity
    FROM jsonb_array_elements(p_items) AS item
    GROUP BY
        (item ->> 'product_id')::BIGINT;

    -- 6. Verify products exist
    IF EXISTS (
        SELECT 1
        FROM temp_sale_items tsi
        LEFT JOIN products p
            ON p.id = tsi.product_id
        WHERE p.id IS NULL
    ) THEN
        RAISE EXCEPTION
            'One or more products were not found.';
    END IF;

    -- 7. Lock products involved in sale
    PERFORM p.id
    FROM products p
    INNER JOIN temp_sale_items tsi
        ON tsi.product_id = p.id
    ORDER BY p.id
    FOR UPDATE;

    -- 8. Validate stock
    IF EXISTS (
        SELECT 1
        FROM temp_sale_items tsi
        INNER JOIN products p
            ON p.id = tsi.product_id
        WHERE p.stock < tsi.quantity
    ) THEN

        SELECT
            p.product_name,
            p.stock,
            tsi.quantity
        INTO v_item
        FROM temp_sale_items tsi
        INNER JOIN products p
            ON p.id = tsi.product_id
        WHERE p.stock < tsi.quantity
        LIMIT 1;

        RAISE EXCEPTION
            'Insufficient stock for %. Available: %, requested: %.',
            v_item.product_name,
            v_item.stock,
            v_item.quantity;
    END IF;

    -- 9. Calculate subtotal using database prices
    SELECT
        COALESCE(
            SUM(
                p.selling_price * tsi.quantity
            ),
            0
        )
    INTO v_subtotal
    FROM temp_sale_items tsi
    INNER JOIN products p
        ON p.id = tsi.product_id;

    -- 10. Validate discount
    IF p_discount > v_subtotal THEN
        RAISE EXCEPTION
            'Discount cannot be greater than subtotal.';
    END IF;

    v_total := v_subtotal - p_discount;

    -- 11. Cash received
    IF p_amount_paid IS NULL THEN
        v_amount_received := v_total;
    ELSE
        v_amount_received := p_amount_paid;
    END IF;

    IF v_amount_received < 0 THEN
        RAISE EXCEPTION
            'Amount received cannot be negative.';
    END IF;

    IF v_amount_received < v_total THEN
        RAISE EXCEPTION
            'Amount received is less than total.';
    END IF;

    v_amount_paid := v_total;

    v_change_due :=
        v_amount_received - v_total;

    -- 12. Generate invoice
    v_invoice_number :=
        generate_invoice_number();

    -- 13. Create sale
    INSERT INTO sales (
        invoice_number,
        customer_id,
        subtotal,
        discount,
        total,
        payment_method,
        amount_paid,
        amount_received,
        change_due,
        notes
    )
    VALUES (
        v_invoice_number,
        p_customer_id,
        v_subtotal,
        p_discount,
        v_total,
        COALESCE(
            NULLIF(TRIM(p_payment_method), ''),
            'Cash'
        ),
        v_amount_paid,
        v_amount_received,
        v_change_due,
        NULLIF(TRIM(p_notes), '')
    )
    RETURNING id
    INTO v_sale_id;

    -- 14. Save historical sale-item snapshots
    INSERT INTO sale_items (
        sale_id,
        product_id,
        product_name,
        quantity,
        unit,
        unit_price,
        unit_cost,
        line_total
    )
    SELECT
        v_sale_id,
        p.id,
        p.product_name,
        tsi.quantity,
        p.unit,
        p.selling_price,
        p.purchase_price,
        p.selling_price * tsi.quantity
    FROM temp_sale_items tsi
    INNER JOIN products p
        ON p.id = tsi.product_id;

    -- 15. Deduct stock
    UPDATE products p
    SET stock =
        p.stock - tsi.quantity
    FROM temp_sale_items tsi
    WHERE p.id = tsi.product_id;

    -- 16. Return checkout result
    RETURN jsonb_build_object(
        'success', true,
        'sale_id', v_sale_id,
        'invoice_number', v_invoice_number,
        'customer_id', p_customer_id,
        'subtotal', v_subtotal,
        'discount', p_discount,
        'total', v_total,
        'amount_paid', v_amount_paid,
        'amount_received', v_amount_received,
        'change_due', v_change_due,
        'payment_method',
            COALESCE(
                NULLIF(TRIM(p_payment_method), ''),
                'Cash'
            )
    );

END;
$function$;